# Use official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /{{ docker_working_directory }}

# Copy dependency files first (for caching)
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app code
COPY . .

# Expose the port Flask will run on
EXPOSE {{ container_port }}

# Run the app with Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:{{ container_port }}", "{{ file_name | replace('.py', '') }}:app"]